### ISSUE TITLE
10G connectivity?

### ISSUE THREAD

**Issue by sirjansel0t** [ghostop14/gr-grnet#12]
Is there any chance this supports 10G connectivity?  I'm trying to stream from an RFSOC using one of their 10G connections.  Also, does this implementation use zero copy?  

Thank you.

**Comment by ghostop14** [comment]
Morning sirjansel0t.  Yes sir!  There's no PHY layer dependencies.  When I was working on the blocks at the Allen Telescope Array they were running on a 10 Gig fiber ethernet connection.  Unfortunately it's not zero copy.  It uses the Boost libraries for connectivity.

**Comment by sirjansel0t** [comment]
Any ideas on how to add zero copy on this?  Let me know.  Thank you for the project!

**Comment by ghostop14** [comment]
You're welcome!  I don't think there's a zero-copy approach.  Particular calls need to be made to retrieve the data from boost and the IP stack into memory you can work with, then there's disparate production/consumption rates between the IP stack and GNU Radio, so data needs to be buffered to be consumed as requested, otherwise data would definitely get lost.
